spring:
  application:
    name: itoken-admin
  zipkin:
    base-url: http://123.207.154.78:9411

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://123.207.154.78:8761/eureka/,http://123.207.154.78:8861/eureka/,http://123.207.154.78:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info