spring:
  application:
    name: itoken-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: host
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://123.207.154.78:8761/eureka/,http://123.207.154.78:8861/eureka/,http://123.207.154.78:8961/eureka/
